In [4]:
import pandas as pd

In [5]:
mX13 = pd.read_csv('data/13features_matrix.csv', index_col=False)
mX13

,Eig07_AEA_dm_,HTm,Eig09_AEA_ri_,ATS6m,Mor11u,SpDiam_X,Psi_i_0d,SpMaxA_AEA_dm_,P_VSA_v_2,Mor17v,BP,log_vp,vp
0,0.000,2.558,0.000,0.000,-0.533,2.000,0.093,0.742,67.828,-0.193,147.500000,-0.163905,0.685638
1,-1.505,2.523,0.000,0.113,0.078,2.000,0.026,0.373,25.145,-0.042,178.889000,-0.001051,0.997582
2,-1.350,2.180,0.000,0.202,0.290,2.000,0.024,0.344,42.683,-0.055,205.500000,-1.004329,0.099008
3,-0.382,4.265,-0.198,1.040,0.011,2.000,-0.004,0.302,36.145,0.056,299.000000,-3.008774,0.000980
4,-1.000,3.535,-0.489,1.627,-0.409,2.000,-0.004,0.277,25.145,-0.177,153.796459,-1.254028,0.055715
...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,1.451,4.552,1.069,3.017,-1.977,2.000,0.000,0.178,22.000,-0.706,301.520307,-3.410876,0.000388
308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.012383,-3.911308,0.000123
309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185.012383,-3.911308,0.000123
310,1.035,4.363,0.706,2.815,-1.487,1.973,0.000,0.208,36.145,-0.536,297.571641,-3.239050,0.000577
311,0.956,5.170,0.918,3.278,-2.429,1.983,0.000,0.213,25.145,-0.818,269.045003,-2.689690,0.002043

In [8]:
waka_dragon_df = pd.read_csv("data/waka_dragon_merged.csv")
vY_Imax = waka_dragon_df['Imax'].astype(float)

In [7]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN

pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

X_scaled = pipeline.fit_transform(mX13)

dbscan = DBSCAN(
    eps=2.0,
    min_samples=5
)

clusters = dbscan.fit_predict(X_scaled)

In [9]:
pd.DataFrame({
    'cluster': clusters,
    'Imax': vY_Imax
}).groupby('cluster')['Imax'].agg(['count','mean','std'])

         count       mean        std
cluster
-1          57  40.085789  17.708393
 0         248  38.322621  14.269251
 1           7  71.365714  10.705066